def draw_power_plant():
    print("-----------------------------------")
    print("|               /                 |")
    print("|              /                  |")
    print("|             /                   |")
    print("|            /                    |")
    print("|            ------               |")
    print("|                 /               |")
    print("|                /                |")
    print("|               /                 |")
    print("|              /                  |")
    print("|                                 |")
    print("|                                 |")
    print("|                                 |")
    print("|                                 |")
    print("|                                 |")
    print("|                                 |")
    print("|                                 |")
    print("|                                 |")
    print("|                                 |")
    print("|                                 |")
    print("|                                 |")
    print("|                                 |")
    print("-----------------------------------")
    return
